# Generated by Django 3.2.18 on 2023-04-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugID', models.CharField(max_length=20)),
                ('caseName', models.CharField(max_length=200)),
                ('FwVersion', models.CharField(max_length=20)),
                ('IP', models.CharField(max_length=20)),
                ('nodeName', models.CharField(max_length=200)),
                ('configID', models.CharField(max_length=20)),
            ],
        ),
    ]
